title: Mohammad Sadra Shakouri
description: Developer
url: "https://msadrashakouri.ir"
author: MSadraShakouri

markdown: kramdown
highlighter: rouge

# This makes projects.md → /projects/
permalink: /:title/
